### PR TITLE
Add Dailymotion

### PR DESCRIPTION
**Pull request by Nexus-Gits**

### CODE REVIEW

**Comment by SaurabhKaperwan** [comment]
I think dramacool already present in horis repo

**Comment by SaurabhKaperwan** [comment]
Is horis dramacool not working?

**Comment by Nexus-Gits** [comment]
Its Dailymotion extension not the Dramacool.

**Comment by SaurabhKaperwan** [comment]
Oh sorry but Dailymotion is already present in luna repo

**Comment by SaurabhKaperwan** [comment]
It is just copy paste of luna repo extension

**Pull request closed without merging**
