### PR TITLE
Added Cinedoze

### PR DESCRIPTION
**Pull request by rockhero1234**

### CODE REVIEW

**Comment by SaurabhKaperwan** [comment]
I just tested this and it is returning no links

**Comment by rockhero1234** [comment]
I there any way to get dynamic cookies

**Comment by SaurabhKaperwan** [comment]
If i have time i will check

**Comment by SaurabhKaperwan** [comment]
Now it working fine

**Comment by rockhero1234** [comment]
I was trying dynamic cookies but not working. If it working which i pushed earlier

**Comment by rockhero1234** [comment]
Done 👍

**Pull request merged**
